"""empty message

Revision ID: 4b2a9c368ccc
Revises: c7b14d511146
Create Date: 2025-03-04 20:13:25.798005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2a9c368ccc'
down_revision = 'c7b14d511146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('targeting', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_groups', schema=None) as batch_op:
        batch_op.drop_column('targeting')

    # ### end Alembic commands ###
