"""empty message

Revision ID: 63d7523525b3
Revises: 83b6ccdf8f64
Create Date: 2025-03-04 22:00:44.646395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d7523525b3'
down_revision = '83b6ccdf8f64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_creative_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ads', schema=None) as batch_op:
        batch_op.drop_column('meta_creative_id')

    # ### end Alembic commands ###
