"""empty message

Revision ID: 83b6ccdf8f64
Revises: 4b2a9c368ccc
Create Date: 2025-03-04 20:58:39.214733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b6ccdf8f64'
down_revision = '4b2a9c368ccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_creatives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caption', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_creatives', schema=None) as batch_op:
        batch_op.drop_column('caption')

    # ### end Alembic commands ###
