"""empty message

Revision ID: c7b14d511146
Revises: d093acf71c42
Create Date: 2025-03-04 19:57:40.867910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7b14d511146'
down_revision = 'd093acf71c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_event', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bid_strategy', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bid_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('roas_average_floor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('optimization_goal', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_groups', schema=None) as batch_op:
        batch_op.drop_column('optimization_goal')
        batch_op.drop_column('roas_average_floor')
        batch_op.drop_column('bid_amount')
        batch_op.drop_column('bid_strategy')
        batch_op.drop_column('billing_event')

    # ### end Alembic commands ###
